services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    working_dir: /home/dynamodblocal

  dynamo-init:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/init-dynamo.sh"]
